/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package site.ycsb.fileiointerface;

public class FileIO extends KeyValueIO {
  private transient long swigCPtr;

  protected FileIO(long cPtr, boolean cMemoryOwn) {
    super(JAVAFileIOJNI.FileIO_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileIO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JAVAFileIOJNI.delete_FileIO(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FileIO(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize, boolean recovery, int compactionThreads) {
    this(JAVAFileIOJNI.new_FileIO__SWIG_0(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize, recovery, compactionThreads), true);
  }

  public FileIO(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize, boolean recovery) {
    this(JAVAFileIOJNI.new_FileIO__SWIG_1(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize, recovery), true);
  }

  public FileIO(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize) {
    this(JAVAFileIOJNI.new_FileIO__SWIG_2(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize), true);
  }

  public FileIO(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize) {
    this(JAVAFileIOJNI.new_FileIO__SWIG_3(filePath, blockSize, capacity, postingBlocks, bufferSize), true);
  }

  public FileIO(String filePath, int blockSize, int capacity, int postingBlocks) {
    this(JAVAFileIOJNI.new_FileIO__SWIG_4(filePath, blockSize, capacity, postingBlocks), true);
  }

  public void ShutDown() {
    JAVAFileIOJNI.FileIO_ShutDown(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_int At(int key) {
    return new SWIGTYPE_p_unsigned_int(JAVAFileIOJNI.FileIO_At(swigCPtr, this, key), false);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Get(int key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Get__SWIG_0(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Get(int key, SWIGTYPE_p_std__string value, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Get__SWIG_1(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(value), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Get(String key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Get__SWIG_2(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_MultiGet__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_MultiGet__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_MultiGet__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_MultiGet__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Put(int key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Put__SWIG_0(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Put(String key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Put__SWIG_1(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Merge(int key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Merge__SWIG_0(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Merge(String key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Merge__SWIG_1(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Delete(int key) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Delete__SWIG_0(swigCPtr, this, key), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Delete(String key) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Delete__SWIG_1(swigCPtr, this, key), true);
  }

  public void ForceCompaction() {
    JAVAFileIOJNI.FileIO_ForceCompaction(swigCPtr, this);
  }

  public void GetStat() {
    JAVAFileIOJNI.FileIO_GetStat(swigCPtr, this);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Load(String path, int blockSize, int capacity) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Load(swigCPtr, this, path, blockSize, capacity), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Save(String path) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Save(swigCPtr, this, path), true);
  }

  public boolean Initialize(boolean debug) {
    return JAVAFileIOJNI.FileIO_Initialize__SWIG_0(swigCPtr, this, debug);
  }

  public boolean Initialize() {
    return JAVAFileIOJNI.FileIO_Initialize__SWIG_1(swigCPtr, this);
  }

  public boolean ExitBlockController(boolean debug) {
    return JAVAFileIOJNI.FileIO_ExitBlockController__SWIG_0(swigCPtr, this, debug);
  }

  public boolean ExitBlockController() {
    return JAVAFileIOJNI.FileIO_ExitBlockController__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Checkpoint(String prefix) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.FileIO_Checkpoint(swigCPtr, this, prefix), true);
  }

}
