package site.ycsb.fileiointerface;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FileIOInterface {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FileIOInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileIOInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JAVAFileIOJNI.delete_FileIOInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FileIOInterface(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize, boolean recovery, int compactionThreads) {
    this(JAVAFileIOJNI.new_FileIOInterface__SWIG_0(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize, recovery, compactionThreads), true);
  }

  public FileIOInterface(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize, boolean recovery) {
    this(JAVAFileIOJNI.new_FileIOInterface__SWIG_1(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize, recovery), true);
  }

  public FileIOInterface(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize, int batchSize) {
    this(JAVAFileIOJNI.new_FileIOInterface__SWIG_2(filePath, blockSize, capacity, postingBlocks, bufferSize, batchSize), true);
  }

  public FileIOInterface(String filePath, int blockSize, int capacity, int postingBlocks, int bufferSize) {
    this(JAVAFileIOJNI.new_FileIOInterface__SWIG_3(filePath, blockSize, capacity, postingBlocks, bufferSize), true);
  }

  public FileIOInterface(String filePath, int blockSize, int capacity, int postingBlocks) {
    this(JAVAFileIOJNI.new_FileIOInterface__SWIG_4(filePath, blockSize, capacity, postingBlocks), true);
  }

  public void ShutDown() {
    JAVAFileIOJNI.FileIOInterface_ShutDown(swigCPtr, this);
  }

  public String Get(int key) {
    return JAVAFileIOJNI.FileIOInterface_Get__SWIG_0(swigCPtr, this, key);
  }

  public String Get(String key) {
    return JAVAFileIOJNI.FileIOInterface_Get__SWIG_1(swigCPtr, this, key);
  }

  public boolean MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return JAVAFileIOJNI.FileIOInterface_MultiGet__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout));
  }

  public boolean MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return JAVAFileIOJNI.FileIOInterface_MultiGet__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values));
  }

  public boolean MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return JAVAFileIOJNI.FileIOInterface_MultiGet__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout));
  }

  public boolean MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return JAVAFileIOJNI.FileIOInterface_MultiGet__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values));
  }

  public boolean Put(int key, String value) {
    return JAVAFileIOJNI.FileIOInterface_Put__SWIG_0(swigCPtr, this, key, value);
  }

  public boolean Put(String key, String value) {
    return JAVAFileIOJNI.FileIOInterface_Put__SWIG_1(swigCPtr, this, key, value);
  }

  public boolean Merge(int key, String value) {
    return JAVAFileIOJNI.FileIOInterface_Merge__SWIG_0(swigCPtr, this, key, value);
  }

  public boolean Merge(String key, String value) {
    return JAVAFileIOJNI.FileIOInterface_Merge__SWIG_1(swigCPtr, this, key, value);
  }

  public boolean Delete(int key) {
    return JAVAFileIOJNI.FileIOInterface_Delete__SWIG_0(swigCPtr, this, key);
  }

  public boolean Delete(String key) {
    return JAVAFileIOJNI.FileIOInterface_Delete__SWIG_1(swigCPtr, this, key);
  }

  public void ForceCompaction() {
    JAVAFileIOJNI.FileIOInterface_ForceCompaction(swigCPtr, this);
  }

  public void GetStat() {
    JAVAFileIOJNI.FileIOInterface_GetStat(swigCPtr, this);
  }

  public boolean Load(String path, int blockSize, int capacity) {
    return JAVAFileIOJNI.FileIOInterface_Load(swigCPtr, this, path, blockSize, capacity);
  }

  public boolean Save(String path) {
    return JAVAFileIOJNI.FileIOInterface_Save(swigCPtr, this, path);
  }

  public boolean Initialize(boolean debug) {
    return JAVAFileIOJNI.FileIOInterface_Initialize__SWIG_0(swigCPtr, this, debug);
  }

  public boolean Initialize() {
    return JAVAFileIOJNI.FileIOInterface_Initialize__SWIG_1(swigCPtr, this);
  }

  public boolean ExitBlockController(boolean debug) {
    return JAVAFileIOJNI.FileIOInterface_ExitBlockController__SWIG_0(swigCPtr, this, debug);
  }

  public boolean ExitBlockController() {
    return JAVAFileIOJNI.FileIOInterface_ExitBlockController__SWIG_1(swigCPtr, this);
  }

  public boolean Checkpoint(String prefix) {
    return JAVAFileIOJNI.FileIOInterface_Checkpoint(swigCPtr, this, prefix);
  }

}
