/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package site.ycsb.fileiointerface;

public class JAVAFileIOJNI {
  public final static native void delete_KeyValueIO(long jarg1);
  public final static native void KeyValueIO_ShutDown(long jarg1, KeyValueIO jarg1_);
  public final static native long KeyValueIO_Get__SWIG_0(long jarg1, KeyValueIO jarg1_, String jarg2, long jarg3);
  public final static native long KeyValueIO_Get__SWIG_1(long jarg1, KeyValueIO jarg1_, int jarg2, long jarg3);
  public final static native long KeyValueIO_MultiGet__SWIG_0(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long KeyValueIO_MultiGet__SWIG_1(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3);
  public final static native long KeyValueIO_MultiGet__SWIG_2(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long KeyValueIO_MultiGet__SWIG_3(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3);
  public final static native long KeyValueIO_Put__SWIG_0(long jarg1, KeyValueIO jarg1_, String jarg2, String jarg3);
  public final static native long KeyValueIO_Put__SWIG_1(long jarg1, KeyValueIO jarg1_, int jarg2, String jarg3);
  public final static native long KeyValueIO_Merge(long jarg1, KeyValueIO jarg1_, int jarg2, String jarg3);
  public final static native long KeyValueIO_Delete(long jarg1, KeyValueIO jarg1_, int jarg2);
  public final static native long KeyValueIO_DeleteRange(long jarg1, KeyValueIO jarg1_, int jarg2, int jarg3);
  public final static native void KeyValueIO_ForceCompaction(long jarg1, KeyValueIO jarg1_);
  public final static native void KeyValueIO_GetStat(long jarg1, KeyValueIO jarg1_);
  public final static native boolean KeyValueIO_Initialize__SWIG_0(long jarg1, KeyValueIO jarg1_, boolean jarg2);
  public final static native boolean KeyValueIO_Initialize__SWIG_1(long jarg1, KeyValueIO jarg1_);
  public final static native boolean KeyValueIO_ExitBlockController__SWIG_0(long jarg1, KeyValueIO jarg1_, boolean jarg2);
  public final static native boolean KeyValueIO_ExitBlockController__SWIG_1(long jarg1, KeyValueIO jarg1_);
  public final static native long KeyValueIO_Checkpoint(long jarg1, KeyValueIO jarg1_, String jarg2);
  public final static native long KeyValueIO_StartToScan(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3);
  public final static native long KeyValueIO_NextToScan(long jarg1, KeyValueIO jarg1_, long jarg2, long jarg3);
  public final static native long new_FileIO__SWIG_0(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, boolean jarg7, int jarg8);
  public final static native long new_FileIO__SWIG_1(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, boolean jarg7);
  public final static native long new_FileIO__SWIG_2(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long new_FileIO__SWIG_3(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native long new_FileIO__SWIG_4(String jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void delete_FileIO(long jarg1);
  public final static native void FileIO_ShutDown(long jarg1, FileIO jarg1_);
  public final static native long FileIO_At(long jarg1, FileIO jarg1_, int jarg2);
  public final static native long FileIO_Get__SWIG_0(long jarg1, FileIO jarg1_, int jarg2, long jarg3);
  public final static native long FileIO_Get__SWIG_1(long jarg1, FileIO jarg1_, int jarg2, long jarg3);
  public final static native long FileIO_Get__SWIG_2(long jarg1, FileIO jarg1_, int jarg2, long jarg3, long jarg4);
  public final static native long FileIO_Get__SWIG_3(long jarg1, FileIO jarg1_, String jarg2, long jarg3);
  public final static native long FileIO_MultiGet__SWIG_0(long jarg1, FileIO jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long FileIO_MultiGet__SWIG_1(long jarg1, FileIO jarg1_, long jarg2, long jarg3);
  public final static native long FileIO_MultiGet__SWIG_2(long jarg1, FileIO jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long FileIO_MultiGet__SWIG_3(long jarg1, FileIO jarg1_, long jarg2, long jarg3);
  public final static native long FileIO_Put__SWIG_0(long jarg1, FileIO jarg1_, int jarg2, String jarg3);
  public final static native long FileIO_Put__SWIG_1(long jarg1, FileIO jarg1_, int jarg2, long jarg3);
  public final static native long FileIO_Put__SWIG_2(long jarg1, FileIO jarg1_, String jarg2, String jarg3);
  public final static native long FileIO_Merge__SWIG_0(long jarg1, FileIO jarg1_, int jarg2, String jarg3);
  public final static native long FileIO_Merge__SWIG_1(long jarg1, FileIO jarg1_, String jarg2, String jarg3);
  public final static native long FileIO_Delete__SWIG_0(long jarg1, FileIO jarg1_, int jarg2);
  public final static native long FileIO_Delete__SWIG_1(long jarg1, FileIO jarg1_, String jarg2);
  public final static native void FileIO_ForceCompaction(long jarg1, FileIO jarg1_);
  public final static native void FileIO_GetStat(long jarg1, FileIO jarg1_);
  public final static native long FileIO_Load(long jarg1, FileIO jarg1_, String jarg2, int jarg3, int jarg4);
  public final static native long FileIO_Save(long jarg1, FileIO jarg1_, String jarg2);
  public final static native boolean FileIO_Initialize__SWIG_0(long jarg1, FileIO jarg1_, boolean jarg2);
  public final static native boolean FileIO_Initialize__SWIG_1(long jarg1, FileIO jarg1_);
  public final static native boolean FileIO_ExitBlockController__SWIG_0(long jarg1, FileIO jarg1_, boolean jarg2);
  public final static native boolean FileIO_ExitBlockController__SWIG_1(long jarg1, FileIO jarg1_);
  public final static native long FileIO_Checkpoint(long jarg1, FileIO jarg1_, String jarg2);
  public final static native long new_FileIOInterface__SWIG_0(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, boolean jarg7, int jarg8);
  public final static native long new_FileIOInterface__SWIG_1(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, boolean jarg7);
  public final static native long new_FileIOInterface__SWIG_2(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long new_FileIOInterface__SWIG_3(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native long new_FileIOInterface__SWIG_4(String jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void FileIOInterface_ShutDown(long jarg1, FileIOInterface jarg1_);
  public final static native byte[] FileIOInterface_GetByteArray(long jarg1, FileIOInterface jarg1_, int jarg2);
  public final static native boolean FileIOInterface_Get__SWIG_0(long jarg1, FileIOInterface jarg1_, int jarg2, long jarg3);
  public final static native String FileIOInterface_Get__SWIG_1(long jarg1, FileIOInterface jarg1_, int jarg2);
  public final static native String FileIOInterface_Get__SWIG_2(long jarg1, FileIOInterface jarg1_, String jarg2);
  public final static native boolean FileIOInterface_MultiGet__SWIG_0(long jarg1, FileIOInterface jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native boolean FileIOInterface_MultiGet__SWIG_1(long jarg1, FileIOInterface jarg1_, long jarg2, long jarg3);
  public final static native boolean FileIOInterface_MultiGet__SWIG_2(long jarg1, FileIOInterface jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native boolean FileIOInterface_MultiGet__SWIG_3(long jarg1, FileIOInterface jarg1_, long jarg2, long jarg3);
  public final static native boolean FileIOInterface_Put__SWIG_0(long jarg1, FileIOInterface jarg1_, int jarg2, String jarg3);
  public final static native boolean FileIOInterface_Put__SWIG_1(long jarg1, FileIOInterface jarg1_, int jarg2, byte[] jarg3);
  public final static native boolean FileIOInterface_Put__SWIG_2(long jarg1, FileIOInterface jarg1_, String jarg2, String jarg3);
  public final static native boolean FileIOInterface_Merge__SWIG_0(long jarg1, FileIOInterface jarg1_, int jarg2, String jarg3);
  public final static native boolean FileIOInterface_Merge__SWIG_1(long jarg1, FileIOInterface jarg1_, String jarg2, String jarg3);
  public final static native boolean FileIOInterface_Delete__SWIG_0(long jarg1, FileIOInterface jarg1_, int jarg2);
  public final static native boolean FileIOInterface_Delete__SWIG_1(long jarg1, FileIOInterface jarg1_, String jarg2);
  public final static native void FileIOInterface_ForceCompaction(long jarg1, FileIOInterface jarg1_);
  public final static native void FileIOInterface_GetStat(long jarg1, FileIOInterface jarg1_);
  public final static native boolean FileIOInterface_Load(long jarg1, FileIOInterface jarg1_, String jarg2, int jarg3, int jarg4);
  public final static native boolean FileIOInterface_Save(long jarg1, FileIOInterface jarg1_, String jarg2);
  public final static native boolean FileIOInterface_Initialize__SWIG_0(long jarg1, FileIOInterface jarg1_, boolean jarg2);
  public final static native boolean FileIOInterface_Initialize__SWIG_1(long jarg1, FileIOInterface jarg1_);
  public final static native boolean FileIOInterface_ExitBlockController__SWIG_0(long jarg1, FileIOInterface jarg1_, boolean jarg2);
  public final static native boolean FileIOInterface_ExitBlockController__SWIG_1(long jarg1, FileIOInterface jarg1_);
  public final static native boolean FileIOInterface_Checkpoint(long jarg1, FileIOInterface jarg1_, String jarg2);
  public final static native void delete_FileIOInterface(long jarg1);
  public final static native long FileIO_SWIGUpcast(long jarg1);
}
