package site.ycsb.fileiointerface;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class KeyValueIO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyValueIO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyValueIO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JAVAFileIOJNI.delete_KeyValueIO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void ShutDown() {
    JAVAFileIOJNI.KeyValueIO_ShutDown(swigCPtr, this);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Get(String key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Get__SWIG_0(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Get(int key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Get__SWIG_1(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_MultiGet__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_std__string_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_MultiGet__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values, SWIGTYPE_p_std__chrono__microseconds timeout) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_MultiGet__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values), SWIGTYPE_p_std__chrono__microseconds.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode MultiGet(SWIGTYPE_p_std__vectorT_int_t keys, SWIGTYPE_p_std__vectorT_std__string_t values) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_MultiGet__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(keys), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(values)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Put(String key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Put__SWIG_0(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Put(int key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Put__SWIG_1(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Merge(int key, String value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Merge(swigCPtr, this, key, value), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Delete(int key) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Delete(swigCPtr, this, key), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode DeleteRange(int start, int end) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_DeleteRange(swigCPtr, this, start, end), true);
  }

  public void ForceCompaction() {
    JAVAFileIOJNI.KeyValueIO_ForceCompaction(swigCPtr, this);
  }

  public void GetStat() {
    JAVAFileIOJNI.KeyValueIO_GetStat(swigCPtr, this);
  }

  public boolean Initialize(boolean debug) {
    return JAVAFileIOJNI.KeyValueIO_Initialize__SWIG_0(swigCPtr, this, debug);
  }

  public boolean Initialize() {
    return JAVAFileIOJNI.KeyValueIO_Initialize__SWIG_1(swigCPtr, this);
  }

  public boolean ExitBlockController(boolean debug) {
    return JAVAFileIOJNI.KeyValueIO_ExitBlockController__SWIG_0(swigCPtr, this, debug);
  }

  public boolean ExitBlockController() {
    return JAVAFileIOJNI.KeyValueIO_ExitBlockController__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode Checkpoint(String prefix) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_Checkpoint(swigCPtr, this, prefix), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode StartToScan(SWIGTYPE_p_int key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_StartToScan(swigCPtr, this, SWIGTYPE_p_int.getCPtr(key), SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_SPTAG__ErrorCode NextToScan(SWIGTYPE_p_int key, SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_SPTAG__ErrorCode(JAVAFileIOJNI.KeyValueIO_NextToScan(swigCPtr, this, SWIGTYPE_p_int.getCPtr(key), SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

}
